PKGNAMESUFFIX?=	-sasl

MAINTAINER=	otis@FreeBSD.org
COMMENT=	Postfix 3.5 with Cyrus SASL support

MASTERDIR=	${.CURDIR}/../postfix35

OPTIONS_SLAVE=	SASL

SASL_SLAVE=	yes

.include "${MASTERDIR}/Makefile"
